apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-dj-app
  namespace: py-dj-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: py-dj-app

  template:
    metadata:
      labels:
        app: py-dj-app

    spec:
      containers:
      - name: py-dj-container
        image: finden.azurecr.io/py-dj-app:v3
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 64Mi
            cpu: 40m
          limits:
            memory: 100Mi
            cpu: 100m