apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-oreo-app
  namespace: py-oreo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: py-oreo-app

  template:
    metadata:
      labels:
        app: py-oreo-app

    spec:
      containers:
      - name: py-oreo-container
        image: finden.azurecr.io/py-oreo-app:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 800Mi
            cpu: 500m
