apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-animie-app
  namespace: py-animie-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: py-animie-app

  template:
    metadata:
      labels:
        app: py-animie-app

    spec:
      containers:
      - name: py-animie-container
        image: finden.azurecr.io/py-animie:test
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: 64Mi
            cpu: 40m
          limits:
            memory: 100Mi
            cpu: 100m
