apiVersion: v1
kind: Service

metadata:
  name: httpd-service
  namespace: httpd-webapp
  labels:
    app: httpd-webapp

spec:
  selector:
    app: httpd-webapp

  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

  type: LoadBalancer
